# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schemas.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schemas.proto',
  package='serde',
  serialized_pb=_b('\n\rschemas.proto\x12\x05serde\"\xac\x05\n\x06\x46light\x12\x0f\n\x07\x46L_DATE\x18\x01 \x02(\t\x12\x12\n\nAIRLINE_ID\x18\x02 \x01(\r\x12\x0f\n\x07\x43\x41RRIER\x18\x03 \x01(\t\x12\x10\n\x08TAIL_NUM\x18\x04 \x01(\t\x12\x0e\n\x06\x46L_NUM\x18\x05 \x01(\r\x12\x19\n\x11ORIGIN_AIRPORT_ID\x18\x06 \x01(\r\x12\x1d\n\x15ORIGIN_AIRPORT_SEQ_ID\x18\x07 \x01(\r\x12\x1d\n\x15ORIGIN_CITY_MARKET_ID\x18\x08 \x01(\r\x12\x0e\n\x06ORIGIN\x18\t \x01(\t\x12\x18\n\x10ORIGIN_CITY_NAME\x18\n \x01(\t\x12\x18\n\x10ORIGIN_STATE_ABR\x18\x0b \x01(\t\x12\x19\n\x11ORIGIN_STATE_FIPS\x18\x0c \x01(\r\x12\x17\n\x0fORIGIN_STATE_NM\x18\r \x01(\t\x12\x12\n\nORIGIN_WAC\x18\x0e \x01(\r\x12\x17\n\x0f\x44\x45ST_AIRPORT_ID\x18\x0f \x01(\r\x12\x1b\n\x13\x44\x45ST_AIRPORT_SEQ_ID\x18\x10 \x01(\r\x12\x1b\n\x13\x44\x45ST_CITY_MARKET_ID\x18\x11 \x01(\r\x12\x0c\n\x04\x44\x45ST\x18\x12 \x01(\t\x12\x16\n\x0e\x44\x45ST_CITY_NAME\x18\x13 \x01(\t\x12\x16\n\x0e\x44\x45ST_STATE_ABR\x18\x14 \x01(\t\x12\x17\n\x0f\x44\x45ST_STATE_FIPS\x18\x15 \x01(\r\x12\x15\n\rDEST_STATE_NM\x18\x16 \x01(\t\x12\x10\n\x08\x44\x45ST_WAC\x18\x17 \x01(\r\x12\x11\n\tDEP_DELAY\x18\x18 \x01(\x02\x12\x10\n\x08TAXI_OUT\x18\x19 \x01(\x02\x12\x12\n\nWHEELS_OFF\x18\x1a \x01(\x02\x12\x11\n\tWHEELS_ON\x18\x1b \x01(\x02\x12\x0f\n\x07TAXI_IN\x18\x1c \x01(\x02\x12\x11\n\tARR_DELAY\x18\x1d \x01(\x02\x12\x10\n\x08\x41IR_TIME\x18\x1e \x01(\x02\x12\x10\n\x08\x44ISTANCE\x18\x1f \x01(\x02\",\n\nFlightBook\x12\x1e\n\x07\x66lights\x18\x01 \x03(\x0b\x32\r.serde.Flight')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FLIGHT = _descriptor.Descriptor(
  name='Flight',
  full_name='serde.Flight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FL_DATE', full_name='serde.Flight.FL_DATE', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AIRLINE_ID', full_name='serde.Flight.AIRLINE_ID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CARRIER', full_name='serde.Flight.CARRIER', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TAIL_NUM', full_name='serde.Flight.TAIL_NUM', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FL_NUM', full_name='serde.Flight.FL_NUM', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ORIGIN_AIRPORT_ID', full_name='serde.Flight.ORIGIN_AIRPORT_ID', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ORIGIN_AIRPORT_SEQ_ID', full_name='serde.Flight.ORIGIN_AIRPORT_SEQ_ID', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ORIGIN_CITY_MARKET_ID', full_name='serde.Flight.ORIGIN_CITY_MARKET_ID', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ORIGIN', full_name='serde.Flight.ORIGIN', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ORIGIN_CITY_NAME', full_name='serde.Flight.ORIGIN_CITY_NAME', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ORIGIN_STATE_ABR', full_name='serde.Flight.ORIGIN_STATE_ABR', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ORIGIN_STATE_FIPS', full_name='serde.Flight.ORIGIN_STATE_FIPS', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ORIGIN_STATE_NM', full_name='serde.Flight.ORIGIN_STATE_NM', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ORIGIN_WAC', full_name='serde.Flight.ORIGIN_WAC', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DEST_AIRPORT_ID', full_name='serde.Flight.DEST_AIRPORT_ID', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DEST_AIRPORT_SEQ_ID', full_name='serde.Flight.DEST_AIRPORT_SEQ_ID', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DEST_CITY_MARKET_ID', full_name='serde.Flight.DEST_CITY_MARKET_ID', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DEST', full_name='serde.Flight.DEST', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DEST_CITY_NAME', full_name='serde.Flight.DEST_CITY_NAME', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DEST_STATE_ABR', full_name='serde.Flight.DEST_STATE_ABR', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DEST_STATE_FIPS', full_name='serde.Flight.DEST_STATE_FIPS', index=20,
      number=21, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DEST_STATE_NM', full_name='serde.Flight.DEST_STATE_NM', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DEST_WAC', full_name='serde.Flight.DEST_WAC', index=22,
      number=23, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DEP_DELAY', full_name='serde.Flight.DEP_DELAY', index=23,
      number=24, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TAXI_OUT', full_name='serde.Flight.TAXI_OUT', index=24,
      number=25, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WHEELS_OFF', full_name='serde.Flight.WHEELS_OFF', index=25,
      number=26, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WHEELS_ON', full_name='serde.Flight.WHEELS_ON', index=26,
      number=27, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TAXI_IN', full_name='serde.Flight.TAXI_IN', index=27,
      number=28, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ARR_DELAY', full_name='serde.Flight.ARR_DELAY', index=28,
      number=29, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AIR_TIME', full_name='serde.Flight.AIR_TIME', index=29,
      number=30, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DISTANCE', full_name='serde.Flight.DISTANCE', index=30,
      number=31, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=709,
)


_FLIGHTBOOK = _descriptor.Descriptor(
  name='FlightBook',
  full_name='serde.FlightBook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flights', full_name='serde.FlightBook.flights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=711,
  serialized_end=755,
)

_FLIGHTBOOK.fields_by_name['flights'].message_type = _FLIGHT
DESCRIPTOR.message_types_by_name['Flight'] = _FLIGHT
DESCRIPTOR.message_types_by_name['FlightBook'] = _FLIGHTBOOK

Flight = _reflection.GeneratedProtocolMessageType('Flight', (_message.Message,), dict(
  DESCRIPTOR = _FLIGHT,
  __module__ = 'schemas_pb2'
  # @@protoc_insertion_point(class_scope:serde.Flight)
  ))
_sym_db.RegisterMessage(Flight)

FlightBook = _reflection.GeneratedProtocolMessageType('FlightBook', (_message.Message,), dict(
  DESCRIPTOR = _FLIGHTBOOK,
  __module__ = 'schemas_pb2'
  # @@protoc_insertion_point(class_scope:serde.FlightBook)
  ))
_sym_db.RegisterMessage(FlightBook)


# @@protoc_insertion_point(module_scope)
